% ---------------------------------------------------------------------
% EG author guidelines plus sample file for EG publication using LaTeX2e input
% D.Fellner, v2.02, Jan 25, 2017


\title[Structure-Aware Generative Models]%
      {Learning Structure-Aware Generative Models for 3D Shapes}

% for anonymous conference submission please enter your SUBMISSION ID
% instead of the author's name (and leave the affiliation blank) !!
% for final version: please provide your *own* ORCID in the brackets following \orcid; see https://orcid.org/ for more details.
\author[S. Chaudhuri \& K. Xu \& D. Ritchie \& H. Zhang]
{\parbox{\textwidth}{\centering S. Chaudhuri$^{2}$\orcid{0000-0001-5923-423X},
        \quad K. Xu$^{1}$\orcid{0000-0001-7756-0901},
        \quad D. Ritchie$^{3}$\orcid{0000-0001-5923-423X},
        \quad H. Zhang$^{4}$\orcid{0000-0001-5923-423X}
        }
        \\
% For Computer Graphics Forum: Please use the abbreviation of your first name.
{\parbox{\textwidth}{\centering $^1$ Adobe Research and IIT Bombay, India\\
         $^2$ National University of Defense Technology, China\\
         $^3$ Brown University, USA\\
         $^4$ Simon Fraser University, Canada
       }
}
}
% ------------------------------------------------------------------------

% if the Editors-in-Chief have given you the data, you may uncomment
% the following five lines and insert it here
%
% \volume{36}   % the volume in which the issue will be published;
% \issue{1}     % the issue number of the publication
% \pStartPage{1}      % set starting page


%-------------------------------------------------------------------------
\begin{document}

% uncomment for using teaser
% \teaser{
%  \includegraphics[width=\linewidth]{eg_new}
%  \centering
%   \caption{New EG Logo}
% \label{fig:teaser}
%}

\maketitle
%-------------------------------------------------------------------------
\begin{abstract}
   The ABSTRACT is to be in fully-justified italicized text, 
   between two horizontal lines,
   in one-column format, 
   below the author and affiliation information. 
   Use the word ``Abstract'' as the title, in 9-point Times, boldface type, 
   left-aligned to the text, initially capitalized. 
   The abstract is to be in 9-point, single-spaced type.
   The abstract may be up to 3 inches (7.62 cm) long. \\
   Leave one blank line after the abstract, 
   then add the subject categories according to the ACM Classification Index   
\end{abstract}  
%-------------------------------------------------------------------------
\section{Introduction}

Some background.

%-------------------------------------------------------------------------
\section{Presenters Details}
Name(s)
Institution(s)
Email address(es)
URL(s)

%-------------------------------------------------------------------------
\subsection{Tutorial Details}
Title of the tutorial.

Keywords.

Half or full day tutorial (either 2×90 minutes or 4×90 minutes)

A detailed outline of the tutorial.

A statement on the necessary background and potential target audience for the tutorial.

A brief resume of the presenter(s) indicating their background in the area the tutorial addresses.


\end{document}
